# Big Query to download Ethereum data
-  The following code has been taken from the kaggle notebook as reference.
- A service account needs to be created.
- bigquery and db-mbs library needs to be installed.

In [1]:
# %pip install db-dtypes
# %pip install google-cloud-bigquery

In [2]:
from google.cloud import bigquery
import pandas as pd
import os
from google.cloud import bigquery
import pandas_gbq
from tqdm import tqdm
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

In [3]:
# query = """
# SELECT 
#   SUM(value/POWER(10,18)) AS sum_tx_ether,
#   AVG(gas_price*(receipt_gas_used/POWER(10,18))) AS avg_tx_gas_cost,
#   DATE(timestamp) AS tx_date
# FROM
#   `bigquery-public-data.crypto_ethereum.transactions` AS transactions,
#   `bigquery-public-data.crypto_ethereum.blocks` AS blocks
# WHERE TRUE
#   AND transactions.block_number = blocks.number
#   AND receipt_status = 1
#   AND value > 0
# GROUP BY tx_date
# HAVING tx_date >= '2015-01-01' AND tx_date <= '2023-12-31'
# ORDER BY tx_date
# """
# query_job = client.query(query)

# iterator = query_job.result(timeout=90)
# rows = list(query_job)

# # Transform the rows into a nice pandas dataframe
# df = pd.DataFrame(data=[list(x.values()) for x in rows], columns=list(rows[0].keys()))

# # Look at the first 10
# df.tail(3)

# Block table and the attributes from 2015 to 2018
- The following query explores all the attributes of the block

- The following query works if we omit 'hash' attribute. 
- We need to fix the hash attribute error issue.

Test Query

In [4]:
# This works on my pc and on kaggle
query2 = """ 
SELECT 
  DATE(timestamp) AS timestamp,
  number AS block_number,
  blocks.hash AS hsh,
  parent_hash,
  nonce,
  miner,
  difficulty,
  size,
  gas_limit,
  gas_used,
  transaction_count
  base_fee_per_gas
  
FROM
  bigquery-public-data.crypto_ethereum.blocks AS blocks
WHERE
  DATE(timestamp) >= '2022-09-15' AND DATE(timestamp) <= '2023-03-01'
ORDER BY timestamp
"""

In [5]:

# Execute the query and convert the results to a Pandas DataFrame
df2=  pandas_gbq.read_gbq(
    query2, project_id=client.project, progress_bar_type='tqdm')
df2.head()

Downloading: 100%|██████████|

,timestamp,block_number,hsh,parent_hash,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
0,2022-09-15,15537127,0xf2ed97d34c9caab9f8038a9c982c3576b5f0ce04917d...,0x014ec824587991134fa42b2837427b34f5ac78624c6e...,0x04109da2981a4aac,0x1ad91ee08f21be3de0ba2ba6918e714da6b45836,10921143718073146.000000000,3582,29999858,438065,10
1,2022-09-15,15535835,0x0b44e425fceeb8eade178a8fc908371ee8105c41767e...,0xef292d6580ced0b7a0f575838cd11e5642ac02c6dd6f...,0x0750fc49b33e4260,0x2daa35962a6d43eb54c48367b33d0b379c930e5e,11644166392685177.000000000,67218,29941324,12464610,144
2,2022-09-15,15537090,0x580e800f4641824db890d73ece97e51cb997e12b6c06...,0xd1af7d32e8e67a4b2ccbe17734e4ace4ec6b5e329397...,0xf4e4d4de5e0cedd5,0x433022c4066558e7a32d850f02d2da5ca782174d,11029579071446300.000000000,46237,30029266,11190841,207
3,2022-09-15,15539374,0xf3d705526676a99b0bbf376245cb0367acd328857261...,0x4a9dcbe678780a5532a4e786af97454e6933a9416e81...,0x0000000000000000,0x1cedc0f3af8f9841b0a1f5c1a4ddc6e1a1629074,0E-9,48843,29970705,13748230,189
4,2022-09-15,15541006,0x1214f637aa4f7fd009147ee742ba74d4dd22336bc0cf...,0x36c59ab63182b6124e10fdd30ca9761d05807e9a26f5...,0x0000000000000000,0x1cedc0f3af8f9841b0a1f5c1a4ddc6e1a1629074,0E-9,127258,29970705,29963432,370

In [6]:
df2.tail()

,timestamp,block_number,hsh,parent_hash,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
1201408,2023-03-01,16735907,0x5b382a2169598b998994cfd361d28025aff9835020ed...,0xb9265be1927678eab3b80732ffa347ff47bc8cedb33f...,0x0000000000000000,0xdafea492d9c6733ae3d56b7ed1adb60692c98bc5,0E-9,175577,30000000,15633746,163
1201409,2023-03-01,16731869,0x30dbd7726e8bd2aa127d4584eb1474b2a72353460386...,0x7d50edb98c507c63319e2d775bcea75b06d2fd6cfe10...,0x0000000000000000,0xc9d945721ed37c6451e457b3c7f1e0cec42417fb,0E-9,180006,30000000,18589573,164
1201410,2023-03-01,16733996,0x73360aae3d92192400a1887ef6a531c1134ba0c450c4...,0x752429dd6335106c5d7158861546c070e25a59f88e8d...,0x0000000000000000,0x388c818ca8b9251b393131c08a736a67ccb19297,0E-9,297612,30000000,20531781,164
1201411,2023-03-01,16730521,0xe20fd451ce862dc6ba164e74ab4ade4d94a6d89b9ebc...,0x7a4e3e74208bca7aea05364926889fcac8fd3836d3fb...,0x0000000000000000,0x1f9090aae28b8a3dceadf281b0f12828e676c326,0E-9,200331,30000000,22111384,166
1201412,2023-03-01,16733922,0x80e9fa182d2f12e272d6b79cc7c596e7681dd6e96c5a...,0x882e3ab7a3b846680c1b51bb10bbaf0ca014b2f57911...,0x0000000000000000,0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5,0E-9,55434,30000000,11698532,170

In [7]:
# Exporting the dataframe to a text file:
df2.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/block_Pos.txt",sep=',')

In [8]:
export_df = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/block_Pos.txt',sep=',')
export_df.head(3)

,Unnamed: 0,timestamp,block_number,hsh,parent_hash,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
0,0,2022-09-15,15537127,0xf2ed97d34c9caab9f8038a9c982c3576b5f0ce04917d...,0x014ec824587991134fa42b2837427b34f5ac78624c6e...,0x04109da2981a4aac,0x1ad91ee08f21be3de0ba2ba6918e714da6b45836,1.092114e+16,3582,29999858,438065,10
1,1,2022-09-15,15535835,0x0b44e425fceeb8eade178a8fc908371ee8105c41767e...,0xef292d6580ced0b7a0f575838cd11e5642ac02c6dd6f...,0x0750fc49b33e4260,0x2daa35962a6d43eb54c48367b33d0b379c930e5e,1.164417e+16,67218,29941324,12464610,144
2,2,2022-09-15,15537090,0x580e800f4641824db890d73ece97e51cb997e12b6c06...,0xd1af7d32e8e67a4b2ccbe17734e4ace4ec6b5e329397...,0xf4e4d4de5e0cedd5,0x433022c4066558e7a32d850f02d2da5ca782174d,1.102958e+16,46237,30029266,11190841,207

In [9]:
export_df.tail(3)

,Unnamed: 0,timestamp,block_number,hsh,parent_hash,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
1201410,1201410,2023-03-01,16733996,0x73360aae3d92192400a1887ef6a531c1134ba0c450c4...,0x752429dd6335106c5d7158861546c070e25a59f88e8d...,0x0000000000000000,0x388c818ca8b9251b393131c08a736a67ccb19297,0.0,297612,30000000,20531781,164
1201411,1201411,2023-03-01,16730521,0xe20fd451ce862dc6ba164e74ab4ade4d94a6d89b9ebc...,0x7a4e3e74208bca7aea05364926889fcac8fd3836d3fb...,0x0000000000000000,0x1f9090aae28b8a3dceadf281b0f12828e676c326,0.0,200331,30000000,22111384,166
1201412,1201412,2023-03-01,16733922,0x80e9fa182d2f12e272d6b79cc7c596e7681dd6e96c5a...,0x882e3ab7a3b846680c1b51bb10bbaf0ca014b2f57911...,0x0000000000000000,0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5,0.0,55434,30000000,11698532,170

In [10]:
print(len(export_df))

1201413

In [11]:
export_df.columns

Index(['Unnamed: 0', 'timestamp', 'block_number', 'hsh', 'parent_hash',
       'nonce', 'miner', 'difficulty', 'size', 'gas_limit', 'gas_used',
       'base_fee_per_gas'],
      dtype='object')