# Big Query to download Ethereum data
-  The following code has been taken from the kaggle notebook as reference.
- A service account needs to be created.
- bigquery and db-mbs library needs to be installed.

In [ ]:
# %pip install db-dtypes
# %pip install google-cloud-bigquery

In [1]:
from google.cloud import bigquery
import pandas as pd
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

In [ ]:
# query = """
# SELECT 
#   SUM(value/POWER(10,18)) AS sum_tx_ether,
#   AVG(gas_price*(receipt_gas_used/POWER(10,18))) AS avg_tx_gas_cost,
#   DATE(timestamp) AS tx_date
# FROM
#   `bigquery-public-data.crypto_ethereum.transactions` AS transactions,
#   `bigquery-public-data.crypto_ethereum.blocks` AS blocks
# WHERE TRUE
#   AND transactions.block_number = blocks.number
#   AND receipt_status = 1
#   AND value > 0
# GROUP BY tx_date
# HAVING tx_date >= '2015-01-01' AND tx_date <= '2023-12-31'
# ORDER BY tx_date
# """
# query_job = client.query(query)

# iterator = query_job.result(timeout=90)
# rows = list(query_job)

# # Transform the rows into a nice pandas dataframe
# df = pd.DataFrame(data=[list(x.values()) for x in rows], columns=list(rows[0].keys()))

# # Look at the first 10
# df.tail(3)

# Block table and the attributes from 2015 to 2018
- The following query explores all the attributes of the block

- The following query works if we omit 'hash' attribute. 
- We need to fix the hash attribute error issue.

Test Query

In [2]:
# This works on my pc and on kaggle
query2 = """ 
SELECT 
  timestamp,
  number AS block_number,
  blocks.hash AS hsh,
  parent_hash
  nonce,
  miner,
  difficulty,
  size,
  gas_limit,
  gas_used,
  transaction_count
  base_fee_per_gas
  
FROM
  bigquery-public-data.crypto_ethereum.blocks AS blocks
WHERE
  EXTRACT(YEAR FROM timestamp) >= 2015
  AND EXTRACT(YEAR FROM timestamp) <= 2023
ORDER BY timestamp
"""

In [3]:

# Execute the query and convert the results to a Pandas DataFrame
df2 = client.query(query2).to_dataframe()
df2.head()

,timestamp,block_number,hsh,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
0,2015-07-30 15:26:28+00:00,1,0x88e96d4537bea4d9c05d12549907b32561d3bf31f45a...,0xd4e56740f876aef8c010b86a40d5f56745a118d0906a...,0x05a56e2d52c817161883f50c441c3228cfe54d9f,17171480576.000000000,537,5000,0,0
1,2015-07-30 15:26:57+00:00,2,0xb495a1d7e6663152ae92708da4843337b958146015a2...,0x88e96d4537bea4d9c05d12549907b32561d3bf31f45a...,0xdd2f1e6e498202e86d8f5442af596580a4f03c2c,17163096064.000000000,544,5000,0,0
2,2015-07-30 15:27:28+00:00,3,0x3d6122660cc824376f11ee842f83addc3525e2dd6756...,0xb495a1d7e6663152ae92708da4843337b958146015a2...,0x5088d623ba0fcf0131e0897a91734a4d83596aa0,17154715646.000000000,1079,5000,0,0
3,2015-07-30 15:27:57+00:00,4,0x23adf5a3be0f5235b36941bcb29b62504278ec5b9cdf...,0x3d6122660cc824376f11ee842f83addc3525e2dd6756...,0xc8ebccc5f5689fa8659d83713341e5ad19349448,17146339321.000000000,1079,5000,0,0
4,2015-07-30 15:28:03+00:00,5,0xf37c632d361e0a93f08ba29b1a2c708d9caa3ee19d1e...,0x23adf5a3be0f5235b36941bcb29b62504278ec5b9cdf...,0x05a56e2d52c817161883f50c441c3228cfe54d9f,17154711556.000000000,537,5000,0,0

In [4]:
df2.tail()

,timestamp,block_number,hsh,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
16685712,2023-02-22 18:19:59+00:00,16685713,0x61cbe079816b57a3fcd584b3ec12688ceb691086b7db...,0x069c6e66249eb823aa6a4801f6fe58aaf4eb972917de...,0x388c818ca8b9251b393131c08a736a67ccb19297,0E-9,294663,30000000,18321043,172
16685713,2023-02-22 18:20:11+00:00,16685714,0x67aa7d3bb6ddf5e4faf82934db534fc7357e5a6693c6...,0x61cbe079816b57a3fcd584b3ec12688ceb691086b7db...,0x5f927395213ee6b95de97bddcb1b2b1c0f16844f,0E-9,114091,30000000,12716093,124
16685714,2023-02-22 18:20:23+00:00,16685715,0x6f7d484a590d63f112008785da19210743c5b8903084...,0x67aa7d3bb6ddf5e4faf82934db534fc7357e5a6693c6...,0xdafea492d9c6733ae3d56b7ed1adb60692c98bc5,0E-9,201291,30000000,16422195,166
16685715,2023-02-22 18:20:35+00:00,16685716,0x54f173515eebea00b1c81c915d93919b7413d34f33be...,0x6f7d484a590d63f112008785da19210743c5b8903084...,0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5,0E-9,81485,30000000,15717443,280
16685716,2023-02-22 18:20:47+00:00,16685717,0x99f6c116c84127f12b423236f288f1e4f3570a2b71c9...,0x54f173515eebea00b1c81c915d93919b7413d34f33be...,0x690b9a9e9aa1c9db991c7721a92d351db4fac990,0E-9,79643,30000000,14306572,210

In [5]:
# Exporting the dataframe to a text file:
df2.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/block.txt",sep=',')

In [6]:
export_df = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/block.txt',sep=',')
export_df.head(3)

,Unnamed: 0,timestamp,block_number,hsh,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
0,0,2015-07-30 15:26:28+00:00,1,0x88e96d4537bea4d9c05d12549907b32561d3bf31f45a...,0xd4e56740f876aef8c010b86a40d5f56745a118d0906a...,0x05a56e2d52c817161883f50c441c3228cfe54d9f,1.717148e+10,537,5000,0,0
1,1,2015-07-30 15:26:57+00:00,2,0xb495a1d7e6663152ae92708da4843337b958146015a2...,0x88e96d4537bea4d9c05d12549907b32561d3bf31f45a...,0xdd2f1e6e498202e86d8f5442af596580a4f03c2c,1.716310e+10,544,5000,0,0
2,2,2015-07-30 15:27:28+00:00,3,0x3d6122660cc824376f11ee842f83addc3525e2dd6756...,0xb495a1d7e6663152ae92708da4843337b958146015a2...,0x5088d623ba0fcf0131e0897a91734a4d83596aa0,1.715472e+10,1079,5000,0,0

In [7]:
export_df.tail(3)

,Unnamed: 0,timestamp,block_number,hsh,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
16685714,16685714,2023-02-22 18:20:23+00:00,16685715,0x6f7d484a590d63f112008785da19210743c5b8903084...,0x67aa7d3bb6ddf5e4faf82934db534fc7357e5a6693c6...,0xdafea492d9c6733ae3d56b7ed1adb60692c98bc5,0.0,201291,30000000,16422195,166
16685715,16685715,2023-02-22 18:20:35+00:00,16685716,0x54f173515eebea00b1c81c915d93919b7413d34f33be...,0x6f7d484a590d63f112008785da19210743c5b8903084...,0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5,0.0,81485,30000000,15717443,280
16685716,16685716,2023-02-22 18:20:47+00:00,16685717,0x99f6c116c84127f12b423236f288f1e4f3570a2b71c9...,0x54f173515eebea00b1c81c915d93919b7413d34f33be...,0x690b9a9e9aa1c9db991c7721a92d351db4fac990,0.0,79643,30000000,14306572,210

In [8]:
print(len(export_df))

16685717

In [9]:
export_df.columns

Index(['Unnamed: 0', 'timestamp', 'block_number', 'hsh', 'nonce', 'miner',
       'difficulty', 'size', 'gas_limit', 'gas_used', 'base_fee_per_gas'],
      dtype='object')