In [4]:
from google.cloud import bigquery
import pandas as pd
import os
from google.cloud import bigquery
import pandas_gbq
from tqdm import tqdm
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

In [5]:
query3 = """ 
SELECT 
  address,
  is_erc20,
  is_erc721,
  DATE(block_timestamp) AS block_timestamp,
  block_number,

FROM
  bigquery-public-data.crypto_ethereum.contracts as contracts
WHERE
  #address = '0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95'
  DATE(block_timestamp) >= '2022-08-18' AND DATE(block_timestamp) <= '2023-08-18'
  #DATE(block_timestamp) >= '2022-09-15' AND DATE(block_timestamp) <= '2023-03-01'
  
ORDER BY block_timestamp
"""

In [6]:
df2 = pandas_gbq.read_gbq(
    query3, project_id=client.project, progress_bar_type='tqdm')

df2.head()

Downloading: 100%|██████████|

,address,is_erc20,is_erc721,block_timestamp,block_number
0,0x054d55c718b9d53151b1cfcb7e3512ec44634cfb,False,False,2022-08-18,15367435
1,0xc23d0e845768ffb659b9f42ea4fff7e68245b18e,False,False,2022-08-18,15363099
2,0x79677b5107828865264c391d632c6688597bcdcf,False,False,2022-08-18,15363356
3,0xc884a29e418603684d9e9a2c509828b69b9c5568,False,False,2022-08-18,15366435
4,0x070a46da405c51e146ddbf39dd3207aaaafba8ae,False,False,2022-08-18,15367208

In [4]:
df2.tail()

,address,is_erc20,is_erc721,block_timestamp,block_number
6435863,0x4aa1a830590d6e5f577cac1c6a16cf2584c97b73,False,True,2023-03-01,16731017
6435864,0x8832472561887103f75af2dd18f6a41353d3360e,False,False,2023-03-01,16731353
6435865,0x5807f74703266b9594a93ce1f4a6ca385818faf4,False,False,2023-03-01,16733570
6435866,0x7ab16ed27ab8b22cb625db55c0e58521969cb091,False,False,2023-03-01,16731407
6435867,0x6404b7adce2cd5f6bcebdf6e513e472e612f2291,False,False,2023-03-01,16733614

In [5]:
# Exporting the dataframe to a text file:
df2.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/contrats_Pos.txt",sep=',')

In [6]:
export_df = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/contrats_Pos.txt',sep=',')
export_df.head(3)

,Unnamed: 0,address,is_erc20,is_erc721,block_timestamp,block_number
0,0,0xf4ebde40553f36b1fd35a9c610ec32b460c0cf77,False,False,2022-09-15,15538169
1,1,0x049a2c9790267e32ee085cf35ff86513ebd13d5e,False,False,2022-09-15,15538169
2,2,0x556d85d042cc80d2be019bf8d6c308dcf121d3b6,False,False,2022-09-15,15538169

In [7]:
export_df.tail(3)

,Unnamed: 0,address,is_erc20,is_erc721,block_timestamp,block_number
6435865,6435865,0x5807f74703266b9594a93ce1f4a6ca385818faf4,False,False,2023-03-01,16733570
6435866,6435866,0x7ab16ed27ab8b22cb625db55c0e58521969cb091,False,False,2023-03-01,16731407
6435867,6435867,0x6404b7adce2cd5f6bcebdf6e513e472e612f2291,False,False,2023-03-01,16733614

In [8]:
print(len(export_df))

6435868

In [9]:
export_df.columns

Index(['Unnamed: 0', 'address', 'is_erc20', 'is_erc721', 'block_timestamp',
       'block_number'],
      dtype='object')