# Big Query to download Ethereum data
-  The following code has been taken from the kaggle notebook as reference.
- A service account needs to be created.
- bigquery and db-mbs library needs to be installed.

In [4]:
# %pip install db-dtypes
# %pip install google-cloud-bigquery

Requirement already satisfied: db-dtypes in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (1.0.5)
Requirement already satisfied: pyarrow>=3.0.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from db-dtypes) (11.0.0)
Requirement already satisfied: numpy<2.0dev,>=1.16.6 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from db-dtypes) (1.22.2)
Requirement already satisfied: packaging>=17.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from db-dtypes) (21.3)
Requirement already satisfied: pandas<2.0dev,>=0.24.2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from db-dtypes) (1.5.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\user\appdata\roaming\python\python39\site-packages (from packaging>=17.0->db-dtypes) (3.0.9)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from pandas<2.0dev,>=0.24.2->db-dtypes) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pandas<2.0dev,>=0.24.2->db-dtypes) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas<2.0dev,>=0.24.2->db-dtypes) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.1.1; however, version 23.0.1 is available.
You should consider upgrading via the 'c:\Users\User\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

Collecting google-cloud-bigquery
  Downloading google_cloud_bigquery-3.5.0-py2.py3-none-any.whl (215 kB)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from google-cloud-bigquery) (3.19.5)
Collecting proto-plus<2.0.0dev,>=1.15.0
  Downloading proto_plus-1.22.2-py3-none-any.whl (47 kB)
Requirement already satisfied: packaging>=20.0.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from google-cloud-bigquery) (21.3)
Collecting google-cloud-core<3.0.0dev,>=1.4.1
  Downloading google_cloud_core-2.3.2-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: requests<3.0.0dev,>=2.21.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from google-cloud-bigquery) (2.28.1)
Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.11.0-py3-none-any.whl (120 kB)
Collecting grpcio<2.0dev,>=1.47.0
  Downloading grpcio-1.51.1-cp39-cp39-win_amd64.whl (3.7 MB)
Collecting google-resumable-media<3.0dev,>=0.6.0
  Downloading google_resumable_media-2.4.1-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in c:\users\user\appdata\roaming\python\python39\site-packages (from google-cloud-bigquery) (2.8.2)
Collecting google-auth<3.0dev,>=2.14.1
  Downloading google_auth-2.16.1-py2.py3-none-any.whl (177 kB)
Collecting googleapis-common-protos<2.0dev,>=1.56.2
  Downloading googleapis_common_protos-1.58.0-py2.py3-none-any.whl (223 kB)
Collecting grpcio-status<2.0dev,>=1.33.2
  Downloading grpcio_status-1.51.1-py3-none-any.whl (5.1 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied: six>=1.9.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from google-auth<3.0dev,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (1.16.0)
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.5.0-cp39-cp39-win_amd64.whl (27 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5
  Downloading protobuf-4.22.0-cp39-cp39-win_amd64.whl (420 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\user\appdata\roaming\python\python39\site-packages (from packaging>=20.0.0->google-cloud-bigquery) (3.0.9)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2.1.1)
Installing collected packages: pyasn1, rsa, pyasn1-modules, protobuf, cachetools, grpcio, googleapis-common-protos, google-auth, grpcio-status, google-crc32c, google-api-core, proto-plus, google-resumable-media, google-cloud-core, google-cloud-bigquery
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.5
    Uninstalling protobuf-3.19.5:
      Successfully uninstalled protobuf-3.19.5
Successfully installed cachetools-5.3.0 google-api-core-2.11.0 google-auth-2.16.1 google-cloud-bigquery-3.5.0 google-cloud-core-2.3.2 google-crc32c-1.5.0 google-resumable-media-2.4.1 googleapis-common-protos-1.58.0 grpcio-1.51.1 grpcio-status-1.51.1 proto-plus-1.22.2 protobuf-4.22.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 rsa-4.9
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
web3 5.31.3 requires protobuf==3.19.5, but you have protobuf 4.22.0 which is incompatible.
WARNING: You are using pip version 21.1.1; however, version 23.0.1 is available.
You should consider upgrading via the 'c:\Users\User\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [2]:
from google.cloud import bigquery
import pandas as pd
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "C:/Users/User/Desktop/blockchain_research/eth-dataset-372206-0985b468a014.json"
client = bigquery.Client()

# Query by Allen Day, GooglCloud Developer Advocate (https://medium.com/@allenday)
query = """
SELECT 
  SUM(value/POWER(10,18)) AS sum_tx_ether,
  AVG(gas_price*(receipt_gas_used/POWER(10,18))) AS avg_tx_gas_cost,
  DATE(timestamp) AS tx_date
FROM
  `bigquery-public-data.crypto_ethereum.transactions` AS transactions,
  `bigquery-public-data.crypto_ethereum.blocks` AS blocks
WHERE TRUE
  AND transactions.block_number = blocks.number
  AND receipt_status = 1
  AND value > 0
GROUP BY tx_date
HAVING tx_date >= '2015-01-01' AND tx_date <= '2023-12-31'
ORDER BY tx_date
"""
query_job = client.query(query)

iterator = query_job.result(timeout=90)
rows = list(query_job)

# Transform the rows into a nice pandas dataframe
df = pd.DataFrame(data=[list(x.values()) for x in rows], columns=list(rows[0].keys()))

# Look at the first 10
df.tail(3)

      sum_tx_ether  avg_tx_gas_cost     tx_date
1952  7.666137e+05         0.002499  2023-02-19
1953  1.130323e+06         0.003400  2023-02-20
1954  9.458600e+05         0.002744  2023-02-21

In [3]:
df.head(3)

   sum_tx_ether  avg_tx_gas_cost     tx_date
0  6.176871e+06         0.000592  2017-10-16
1  1.109204e+07         0.000464  2017-10-17
2  1.459824e+07         0.000494  2017-10-18

# Block table and the attributes from 2015 to 2018
- The following query explores all the attributes of the block

In [19]:
query1 = """ 
SELECT 
  timestamp,
  number AS block_number,
  'hash' as hsh,
  parent_hash,
  nonce,
  miner,
  difficulty,
  size,
  gas_limit,
  gas_used,
  transaction_count
  base_fee_per_gas
  
FROM
  `bigquery-public-data.crypto_ethereum.blocks`
WHERE
  EXTRACT(YEAR FROM timestamp) = 2015
  # AND EXTRACT(YEAR FROM timestamp) <= 2018
ORDER BY timestamp
"""

In [22]:
# Transactions query

In [25]:
# Contracts query

In [27]:
# Token_transfer query

In [29]:
# token query

In [30]:
# Execute the query and convert the results to a Pandas DataFrame
# There is an issue with the 'hash' attribute in the above query, it produces a BadRequest error
# df2 = client.query(query1).to_dataframe()
# df2.head(3)
df2 = client.query(query5)
print(df2)

QueryJob<project=eth-dataset-372206, location=US, id=6b65a0ab-5a92-4da1-89e4-4c717f2daf4b>

- The following query works if we omit 'hash' attribute. 
- We need to fix the hash attribute error issue.

In [20]:
# The following query does not have the 'hash' attributes to be queried. It Works!!!!
# query2 = """ 
# SELECT 
#   timestamp,
#   number AS block_number, 
#   parent_hash
#   nonce,
#   miner,
#   difficulty,
#   size,
#   gas_limit,
#   gas_used,
#   transaction_count
#   base_fee_per_gas
  
# FROM
#   `bigquery-public-data.crypto_ethereum.blocks`
# WHERE
#   EXTRACT(YEAR FROM timestamp) >= 2015
#   AND EXTRACT(YEAR FROM timestamp) <= 2018
# ORDER BY timestamp
# """

In [29]:

# Execute the query and convert the results to a Pandas DataFrame
df2 = client.query(query2).to_dataframe()
df2.head()

In [30]:
# Exporting the dataframe to a text file:
df2.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/block.txt",sep='\t')

In [33]:
export_df = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/block.txt',sep='\t')
export_df.head(3)

,Unnamed: 0,timestamp,block_number,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
0,0,2015-07-30 15:26:28+00:00,1,0x539bd4979fef1ec4,0x05a56e2d52c817161883f50c441c3228cfe54d9f,1.717148e+10,537,5000,0,0
1,1,2015-07-30 15:26:57+00:00,2,0xb853fa261a86aa9e,0xdd2f1e6e498202e86d8f5442af596580a4f03c2c,1.716310e+10,544,5000,0,0
2,2,2015-07-30 15:27:28+00:00,3,0x2e9344e0cbde83ce,0x5088d623ba0fcf0131e0897a91734a4d83596aa0,1.715472e+10,1079,5000,0,0

In [34]:
export_df.tail(3)

,Unnamed: 0,timestamp,block_number,nonce,miner,difficulty,size,gas_limit,gas_used,base_fee_per_gas
6988611,6988611,2018-12-31 23:59:22+00:00,6988612,0x58709a501293367d,0xea674fdde714fd979de3edf0f56aa9716b898ec8,2.512630e+15,15526,8000029,6855179,125
6988612,6988612,2018-12-31 23:59:38+00:00,6988613,0xc226e1c3296e7b0a,0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5,2.512768e+15,5481,8000029,1654731,26
6988613,6988613,2018-12-31 23:59:42+00:00,6988614,0xddfb0738002e1ee4,0x829bd824b016326a401d083b33d092293333a830,2.514132e+15,21421,8007840,7717545,98

In [36]:
print(len(export_df))

6988614

In [37]:
export_df.columns

Index(['Unnamed: 0', 'timestamp', 'block_number', 'nonce', 'miner',
       'difficulty', 'size', 'gas_limit', 'gas_used', 'base_fee_per_gas'],
      dtype='object')