In [32]:
from google.cloud import bigquery
import pandas as pd
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

# Query by Allen Day, GooglCloud Developer Advocate (https://medium.com/@allenday)
query = """
SELECT 
  SUM(value/POWER(10,18)) AS sum_tx_ether,
  AVG(gas_price*(receipt_gas_used/POWER(10,18))) AS avg_tx_gas_cost,
  DATE(timestamp) AS tx_date
FROM
  `bigquery-public-data.crypto_ethereum.transactions` AS transactions,
  `bigquery-public-data.crypto_ethereum.blocks` AS blocks
WHERE TRUE
  AND transactions.block_number = blocks.number
  AND receipt_status = 1
  AND value > 0
GROUP BY tx_date
HAVING tx_date >= '2015-01-01' AND tx_date <= '2023-12-31'
ORDER BY tx_date
"""

In [34]:
query1 = """ 
SELECT 
  timestamp,
  number AS block_number,
  hash AS block_hash,
  previous_block_hash,
  nonce,
  transactions_root,
  state_root,
  receipts_root,
  miner,
  difficulty,
  total_difficulty,
  size AS block_size_kB,
  gas_limit,
  gas_used,
  transaction_count
FROM
  `bigquery-public-data.crypto_ethereum.blocks`
WHERE
  EXTRACT(YEAR FROM timestamp) >= 2015
  AND EXTRACT(YEAR FROM timestamp) <= 2022
ORDER BY timestamp
"""

SELECT
  timestamp,
  number AS block_number,
  hash AS block_hash,
  previous_block_hash,
  nonce,
  transactions_root,
  state_root,
  receipts_root,
  miner,
  difficulty,
  total_difficulty,
  size AS block_size_kB,
  gas_limit,
  gas_used,
  transaction_count
FROM
  `bigquery-public-data.crypto_ethereum.blocks`
WHERE
  EXTRACT(YEAR FROM timestamp) >= 2015
  AND EXTRACT(YEAR FROM timestamp) <= 2022
ORDER BY timestamp

In [35]:
query_job1 = client.query(query1)
print(query_job1)

QueryJob<project=top-amplifier-218404, location=US, id=8825996b-7675-4573-9a12-d43b61dadfdf>

In [33]:
query_job = client.query(query)

iterator = query_job.result(timeout=90)
rows = list(query_job)

# Transform the rows into a nice pandas dataframe
df = pd.DataFrame(data=[list(x.values()) for x in rows], columns=list(rows[0].keys()))

# Look at the first 10
df.tail(10)

      sum_tx_ether  avg_tx_gas_cost     tx_date
1945  6.033791e+05         0.001762  2023-02-12
1946  1.656191e+06         0.002212  2023-02-13
1947  1.458673e+06         0.003115  2023-02-14
1948  1.602448e+06         0.003169  2023-02-15
1949  1.690511e+06         0.003080  2023-02-16
1950  1.007083e+06         0.003225  2023-02-17
1951  8.031546e+05         0.002464  2023-02-18
1952  7.666137e+05         0.002499  2023-02-19
1953  1.130323e+06         0.003400  2023-02-20
1954  4.423076e+05         0.002543  2023-02-21

In [38]:
df.head()

   sum_tx_ether  avg_tx_gas_cost     tx_date
0  6.176871e+06         0.000592  2017-10-16
1  1.109204e+07         0.000464  2017-10-17
2  1.459824e+07         0.000494  2017-10-18
3  1.236437e+07         0.000456  2017-10-19
4  1.135642e+07         0.000413  2017-10-20

In [37]:
df1 = pd.read_sql(query1, con = )

TypeError: read_sql() missing 1 required positional argument: 'con'