In [1]:
from google.cloud import bigquery
import pandas as pd
import os
from google.cloud import bigquery
import pandas_gbq
from tqdm import tqdm
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

In [2]:
query1 = """ 
SELECT 
  token_address,
  from_address,
  to_address,
  value,
  transaction_hash,
  DATE(block_timestamp) AS block_timestamp,
  block_number,
  block_hash

FROM
  bigquery-public-data.crypto_ethereum.token_transfers as token_transfers
WHERE
   DATE(block_timestamp) > '2022-11-06' AND DATE(block_timestamp) <= '2022-11-15'
   #block_timestamp > timestamp_sub(current_timestamp, INTERVAL 1 DAY)
ORDER BY block_timestamp
"""

In [3]:
df1 = pandas_gbq.read_gbq(
    query1, project_id=client.project, progress_bar_type='tqdm')

df1.head()

Downloading: 100%|██████████|

,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
0,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x3904cf8dd157e0814fbb4c983237d989d4f97ea9,10000000000000000,0xcc5ab1ddb984313669e4f210c154bfbd0aa200c8c09b...,2022-11-07,15917079,0x8b76898a83d20a636fe6182d1384ac844ddcb9105a7e...
1,0x77e46724fd97248e6fa9ea2aca03026b00ec8f07,0x0000000000000000000000000000000000000000,0x2321fc0c41a6888d02286a9799ea7b73bcdfd96a,1028,0x91b48a993002b084cd7eb8f8b79b9aacd8ab66df602e...,2022-11-07,15917335,0xb913323ab71421c26f1100ded0f6660e8f4107e86d44...
2,0x9db475371b5cc2913d3219f72e16a3f101339a05,0x8b62461f1f3120bdb0a26e1633cfd2f4e683b848,0x9b8b24e3d406627984eb3782f358ac00431bd93a,5585,0x9cac3945f106b2b4ac65cef954e1c6767824fde07e2a...,2022-11-07,15919127,0x581551f755b2801394c5874911bcac75047480ec122c...
3,0xdac17f958d2ee523a2206206994597c13d831ec7,0x122868dc5e6443ed775e0b2e960291f32ed34688,0x2599215e5014c029701304f920433d5b3b704792,9400000000,0xa5e83d4338ac161ce659e617fc7be3b3ce8771eae81d...,2022-11-07,15919383,0xa21653f1a99f1c1f435f6b4490a23a3f92350a836fbd...
4,0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0,0x290a6a7460b308ee3f19023d2d00de604bcf5b42,0x6146d22d14653dfc66aa20424c0b78834810f8c3,17459729835324471380,0x6080ef1733a1e8b2cd7bf752fe86f2e038384f878de4...,2022-11-07,15920151,0x816a5c3f6e1b438c7ae42cf36acbb79c445b7c04ec7f...

In [4]:
# Exporting the dataframe to a text file:
df1.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/token_transfer_Pos_2022_11_06_11_15.txt",sep=',')

In [5]:
export_df1 = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/token_transfer_Pos_2022_11_06_11_15.txt',sep=',')
export_df1.head(3)

,Unnamed: 0,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
0,0,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x3904cf8dd157e0814fbb4c983237d989d4f97ea9,10000000000000000,0xcc5ab1ddb984313669e4f210c154bfbd0aa200c8c09b...,2022-11-07,15917079,0x8b76898a83d20a636fe6182d1384ac844ddcb9105a7e...
1,1,0x77e46724fd97248e6fa9ea2aca03026b00ec8f07,0x0000000000000000000000000000000000000000,0x2321fc0c41a6888d02286a9799ea7b73bcdfd96a,1028,0x91b48a993002b084cd7eb8f8b79b9aacd8ab66df602e...,2022-11-07,15917335,0xb913323ab71421c26f1100ded0f6660e8f4107e86d44...
2,2,0x9db475371b5cc2913d3219f72e16a3f101339a05,0x8b62461f1f3120bdb0a26e1633cfd2f4e683b848,0x9b8b24e3d406627984eb3782f358ac00431bd93a,5585,0x9cac3945f106b2b4ac65cef954e1c6767824fde07e2a...,2022-11-07,15919127,0x581551f755b2801394c5874911bcac75047480ec122c...

In [6]:
export_df1.tail(3)

,Unnamed: 0,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
10655467,10655467,0x2260fac5e5542a773aa44fbcfedf7c193bc2c599,0x57c1e0c2adf6eecdb135bcf9ec5f23b319be2c94,0x9a772018fbd77fcd2d25657e5c547baff3fd7d16,59829153,0x9c63320c1b2be8c77476b42b99e4cff1563c56e4fd7c...,2022-11-15,15976702,0x3169a1a9ac4329ad96dd63801b761c197f9bcd672636...
10655468,10655468,0x3819f64f282bf135d62168c1e513280daf905e06,0x32a5a6ed835617968ba1ac6874ad2c2a2d652dac,0x0000000000000000000000000000000000000000,2162965404880886,0xe988b196568572b5d501877b57b13947f5b381b67c4f...,2022-11-15,15974199,0x8c472a08c98f8dbdc3d8ae3061154e0011c0e8d763c3...
10655469,10655469,0xdac17f958d2ee523a2206206994597c13d831ec7,0x06f530901a2bd9e9853b1f0cf4f56d53afd09754,0x147d4ec93a462c41ad68b463ec43f50d33023d8b,330000000,0xe2fb9635bcab0c55d62eb0896891a7106b54699efa8a...,2022-11-15,15974711,0xd532b5e9ab1aaa899eafcffb941557462e25a2157495...

In [7]:
print(len(export_df1))

10655470

In [8]:
export_df1.columns

Index(['Unnamed: 0', 'token_address', 'from_address', 'to_address', 'value',
       'transaction_hash', 'block_timestamp', 'block_number', 'block_hash'],
      dtype='object')