In [1]:
from google.cloud import bigquery
import pandas as pd
import os
from google.cloud import bigquery
import pandas_gbq
from tqdm import tqdm
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

In [2]:
query5 = """ 
SELECT 
  address,
  name,
  decimals,
  total_supply,
  DATE(block_timestamp) AS block_timestamp,
  block_number,
  block_hash

FROM
  bigquery-public-data.crypto_ethereum.tokens as tokens
WHERE
  DATE(block_timestamp) >= '2022-09-15' AND DATE(block_timestamp) <= '2023-03-01'
  #block_timestamp > timestamp_sub(current_timestamp, INTERVAL 1 DAY)
ORDER BY block_timestamp
"""

In [3]:
df = pandas_gbq.read_gbq(
    query5, project_id=client.project, progress_bar_type='tqdm')

Downloading: 100%|██████████|

In [4]:
df.head()

,address,name,decimals,total_supply,block_timestamp,block_number,block_hash
0,0x3bf56857b865cc76d3ed042cabca213d9ea5bda1,Black Book of Shadows Vol.1,None,0,2022-09-15,15542063,0x3a397c441e7c75697bba8c483252647d3f71e0719a03...
1,0xe4a880a0484b5659323be4bf225cdb7c41b75ca5,Mana - Figo i Samogony,0,400000,2022-09-15,15538939,0x45ba1e8002a5c4be2c37dcf713c22c2959244e66803f...
2,0x098b9786249cfdbd52602a81a8af50be5a84ae91,merge-eth.com,0,1000000,2022-09-15,15537055,0x84f46bf08e9e94a01f0eecb8281e0103019af11758a1...
3,0xe23366cccf6c5318b47621ceac3296d480b5ebc8,merge-eth.io,0,1000000,2022-09-15,15537057,0x66be36a270617f82684f5ef7b8b8c7b4121ade04f398...
4,0x4d380e947cc9ef031624a47c82e1a4b29a23366e,Bitcoin,2,2000000,2022-09-15,15539207,0x3d5756f2c87f1a4a9336a411c55653e49e47a3b2e834...

In [5]:
df.tail()

,address,name,decimals,total_supply,block_timestamp,block_number,block_hash
2623,0x9ea4ebc3974bc15b9050c8375a5cd0c9d2f925fe,TetherUSD,18,100000000000000000000000000,2023-03-01,16736512,0x26be209fd28c62a4380718c1b21e056cbb2d59be8d6a...
2624,0xe4806171aea5513226fbd43d4c6a96fd37093192,Wrapped Ether,18,1000000000,2023-03-01,16734834,0x2edb469da71151d900ab93f9948acd297a206b12035d...
2625,0xa5606d30057a79a8f8474833a04637e2606dc297,Unipilot YFI/WETH Passive Vault,18,39098690000000000000,2023-03-01,16736380,0x9e97f211d448d386189760426f09cda980fbde3e8c99...
2626,0x5d401fb0a405a37ee5f3ea85c494da0c263b6589,Unipilot LINK/WETH Active Vault,18,0,2023-03-01,16733325,0x484edcd2374bd0d3e415f5dbd1e01e1d9364ca003220...
2627,0xeabc9e3eb31a79bbf1a3b20ddabfaa50521c1d8e,Unipilot AAVE/WETH Passive Vault,18,0,2023-03-01,16736455,0x530873a7663f5a0471f8ad2fc2ed9b0f6d8f28146d8c...

In [6]:
# Exporting the dataframe to a text file:
df.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/token_Pos.txt",sep='\t')

In [7]:
export_df = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/token_Pos.txt',sep='\t')
export_df.head(3)

,Unnamed: 0,address,name,decimals,total_supply,block_timestamp,block_number,block_hash
0,0,0x3bf56857b865cc76d3ed042cabca213d9ea5bda1,Black Book of Shadows Vol.1,NaN,0,2022-09-15,15542063,0x3a397c441e7c75697bba8c483252647d3f71e0719a03...
1,1,0xe4a880a0484b5659323be4bf225cdb7c41b75ca5,Mana - Figo i Samogony,0.0,400000,2022-09-15,15538939,0x45ba1e8002a5c4be2c37dcf713c22c2959244e66803f...
2,2,0x098b9786249cfdbd52602a81a8af50be5a84ae91,merge-eth.com,0.0,1000000,2022-09-15,15537055,0x84f46bf08e9e94a01f0eecb8281e0103019af11758a1...

In [8]:
export_df.tail(3)

,Unnamed: 0,address,name,decimals,total_supply,block_timestamp,block_number,block_hash
2625,2625,0xa5606d30057a79a8f8474833a04637e2606dc297,Unipilot YFI/WETH Passive Vault,18.0,39098690000000000000,2023-03-01,16736380,0x9e97f211d448d386189760426f09cda980fbde3e8c99...
2626,2626,0x5d401fb0a405a37ee5f3ea85c494da0c263b6589,Unipilot LINK/WETH Active Vault,18.0,0,2023-03-01,16733325,0x484edcd2374bd0d3e415f5dbd1e01e1d9364ca003220...
2627,2627,0xeabc9e3eb31a79bbf1a3b20ddabfaa50521c1d8e,Unipilot AAVE/WETH Passive Vault,18.0,0,2023-03-01,16736455,0x530873a7663f5a0471f8ad2fc2ed9b0f6d8f28146d8c...

In [9]:
print(len(export_df))

2628

In [10]:
export_df.columns

Index(['Unnamed: 0', 'address', 'name', 'decimals', 'total_supply',
       'block_timestamp', 'block_number', 'block_hash'],
      dtype='object')