In [1]:
from google.cloud import bigquery
import pandas as pd
import os
from google.cloud import bigquery
import pandas_gbq
from tqdm import tqdm
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

In [4]:
query2 = """ 
SELECT 
  token_address,
  from_address,
  to_address,
  value,
  transaction_hash,
  DATE(block_timestamp) AS block_timestamp,
  block_number,
  block_hash

FROM
  bigquery-public-data.crypto_ethereum.token_transfers as token_transfers
WHERE
   DATE(block_timestamp) >= '2022-10-16' AND DATE(block_timestamp) <= '2022-10-16'
   #block_timestamp > timestamp_sub(current_timestamp, INTERVAL 1 DAY)
ORDER BY block_timestamp
"""

In [5]:
df2 = pandas_gbq.read_gbq(
    query2, project_id=client.project, progress_bar_type='tqdm')

df2.head()

ImportError: pandas-gbq requires pydata-google-auth

In [4]:
# Exporting the dataframe to a text file:
df2.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/token_transfer_Pos_2022_10_16_10_25.txt",sep=',')

In [5]:
export_df2 = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/token_transfer_Pos_2022_10_16_10_25.txt',sep=',')
export_df2.head(3)

,Unnamed: 0,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
0,0,0x2559813bbb508c4c79e9ccce4703bcb1f149edd7,0x6028eb8adda090cdf08fb5dfbe873081fd736867,0x5ef9f94c5708b01d67985e46fd53f15cf0da4d2c,3722058775574,0x4420209fd6ff6d3e5592df98fa40b9cb44a295947c0c...,2022-10-16,15759433,0xf7f602c02bf0e3e444bfbd209fd71962b80c6a5aa318...
1,1,0xd17fce1c4c199ff9d02c9674abf52fd35d9d058c,0x919a72a0b680c831786fd4a117a9303868865787,0xb0cbf149ba9e7d0efb63235a08768a7b63f0652f,11834,0x953c6a374502b278197d7d0c3229ac35008d3463edff...,2022-10-16,15760969,0x04f8dbf48e21760e82674d2701d970261538c9a0a876...
2,2,0x00a8b738e453ffd858a7edf03bccfe20412f0eb0,0xfe4a6cc39e088d7990d7c3649da300c62593d68d,0x8e561060b5966e0d9fe08846ebc45e10bddaf754,4000000000000000000000,0xf4cca8532d6f3226349d52fcdfc82e88db758dce485f...,2022-10-16,15761481,0x8189605fc2f09f9a7b7e1eb350c5259a916f6dc70271...

In [6]:
export_df2.tail(3)

,Unnamed: 0,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
11059200,11059200,0xe0d59c9d3166ab99f3631941cc561c9870742609,0xbf0122edfef8486f5f91b80225b22a6b1837684e,0xe0d59c9d3166ab99f3631941cc561c9870742609,219294187407100333376843,0x04d61ca6492588bd1e3db065d5fe1869e9aca05b3589...,2022-10-25,15824690,0x1fdaeeaaddc2d6a773ba5d50d94e30df01c5f59addc3...
11059201,11059201,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x25553828f22bdd19a20e4f12f052903cb474a335,0x688a0ddf250a4f1e1ef71e995573752b0f316896,29700000000000000,0x3e990346b4e7f5538924c2b28d63c2cb5a06c2998be5...,2022-10-25,15827959,0x1fe009ebf5f07895d29d4af07edbc2174eab2f1b94dc...
11059202,11059202,0xd394d568477b31ffba51f6f5f3302a37f490194b,0x9a41d55a5384c22835477a4faf0254ec677b5e1f,0x942c410ba8246cd3a9794df7385e0c3367ce2393,497286257387,0xd2c2d3e7bcb8cee74437dd01f0ae6e61df9a26f8331d...,2022-10-25,15825166,0x1fec39359596f054762f3aae9bb82a7f41b8996ee707...

In [7]:
print(len(export_df2))

11059203

In [8]:
export_df2.columns

Index(['Unnamed: 0', 'token_address', 'from_address', 'to_address', 'value',
       'transaction_hash', 'block_timestamp', 'block_number', 'block_hash'],
      dtype='object')