In [1]:
from google.cloud import bigquery
import pandas as pd
import os
from google.cloud import bigquery
import pandas_gbq
from tqdm import tqdm
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/dr.rubaiyatislam/Documents/big_query/keyfile.json"
client = bigquery.Client()

In [2]:
query3 = """ 
SELECT 
  token_address,
  from_address,
  to_address,
  value,
  transaction_hash,
  DATE(block_timestamp) AS block_timestamp,
  block_number,
  block_hash

FROM
  bigquery-public-data.crypto_ethereum.token_transfers as token_transfers
WHERE
   DATE(block_timestamp) >= '2023-08-18' AND DATE(block_timestamp) <= '2023-08-18'
   #block_timestamp > timestamp_sub(current_timestamp, INTERVAL 1 DAY)
ORDER BY block_timestamp
"""

In [3]:
df3 = pandas_gbq.read_gbq(
    query3, project_id=client.project, progress_bar_type='tqdm')

df3.head()

Downloading: 100%|██████████|

,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
0,0xb478c6245e3d85d6ec3486b62ea872128d562541,0x57bbcb3da0b6983bde4bd8b9c605ebc65fb3b06f,0xb478c6245e3d85d6ec3486b62ea872128d562541,13872653565583204250,0xc0a76178c6a1476e308a16852ea30476e19898e71688...,2023-08-18,17943492,0x062aeec3de0f6800fa94bceb6d70c30c08c6f99f96f1...
1,0x6cca981e8e1e318a696feb455d298fc65227ed8d,0x0ae879fb0f2e630ed3d423eb09e925c63495cfe6,0xbf6084876b8a94bea89f123a3621980ff88ed395,1625720000000000000000,0x6bfa5da66ffce544193da9e3ebba0b87bb943aeeae6b...,2023-08-18,17939177,0xc86fb4167fd64ecd12951882204b926a1dd47f67883f...
2,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad,0x98bb850ff2e55a886a281e37324b72ce4d51e02d,17474237985334200,0x06256b0f4f347c459fe178b1038c1534c80391ed9fe5...,2023-08-18,17944508,0xc0404f0c41614868fb31dae079af3dc5eea841f24663...
3,0x204c1f431a23afaef6294cd128eea822eb9419ba,0x44f3791ad797ddc9144008bf6396124fbcc491b9,0x7c66c8434a91bd5e50995ae4a523513514fcaff8,565191000000,0xed11136177fe8e38a5f30e8a325d4a1b3c1624391c7e...,2023-08-18,17943511,0xf3bb6f8779e1be0a79090862399843a141067421cc5c...
4,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x0821e3cb9d5c653622b6c7b9dceddf3581880d34,0x7a250d5630b4cf539739df2c5dacb4c659f2488d,331416974953458463,0xd6d15259c8b8557b3031dd6b83f89149bde1f35eb66b...,2023-08-18,17939196,0x7c6541f27214711c032541338d8babc1b33f98db93cb...

In [4]:
# Exporting the dataframe to a text file:
df3.to_csv("/Users/dr.rubaiyatislam/Documents/big_query/token_transfer_Pos_2022_10_26_11_05.txt",sep=',')

In [5]:
export_df3 = pd.read_csv('/Users/dr.rubaiyatislam/Documents/big_query/token_transfer_Pos_2022_10_26_11_05.txt',sep=',')
export_df3.head(3)

,Unnamed: 0,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
0,0,0xb478c6245e3d85d6ec3486b62ea872128d562541,0x57bbcb3da0b6983bde4bd8b9c605ebc65fb3b06f,0xb478c6245e3d85d6ec3486b62ea872128d562541,13872653565583204250,0xc0a76178c6a1476e308a16852ea30476e19898e71688...,2023-08-18,17943492,0x062aeec3de0f6800fa94bceb6d70c30c08c6f99f96f1...
1,1,0x6cca981e8e1e318a696feb455d298fc65227ed8d,0x0ae879fb0f2e630ed3d423eb09e925c63495cfe6,0xbf6084876b8a94bea89f123a3621980ff88ed395,1625720000000000000000,0x6bfa5da66ffce544193da9e3ebba0b87bb943aeeae6b...,2023-08-18,17939177,0xc86fb4167fd64ecd12951882204b926a1dd47f67883f...
2,2,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad,0x98bb850ff2e55a886a281e37324b72ce4d51e02d,17474237985334200,0x06256b0f4f347c459fe178b1038c1534c80391ed9fe5...,2023-08-18,17944508,0xc0404f0c41614868fb31dae079af3dc5eea841f24663...

In [6]:
export_df3.tail(3)

,Unnamed: 0,token_address,from_address,to_address,value,transaction_hash,block_timestamp,block_number,block_hash
1241992,1241992,0x8290333cef9e6d528dd5618fb97a76f268f3edd4,0xa9d1e08c7793af67e9d92fe308d5697fb81d3e43,0x0da2e115a73ffc264799f396c4a2e1c59ccfa527,883396789820000000000,0x13c7d05e4bb4665479a4acf3dd75b1e8b0f6f0ed7216...,2023-08-18,17944506,0xe36b7547ba0c05c929153ed320100579f5ddba1bee88...
1241993,1241993,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc4bcaed8570fa0d8ab5a0e6a5cf3b7871f87af82,0xdce92f40cadde2c4e3ea78b8892c540e6bfe2f81,93569855,0x654b4e589fd1861754fb93d042cb2916c5c5ca078a8f...,2023-08-18,17941947,0x01a6f1a6231af74255d214e1955d03e964edf56ef5da...
1241994,1241994,0xbb9fd9fa4863c03c574007ff3370787b9ce65ff6,0x1d9a941da508d9c603128f7776e19910c4fc8d1b,0x55174f68e7fa87b9309920b413233789dc4a9d1d,2425382171034789681125,0xf12f682e1cf6759bb08f019e25e6726435b339b91e83...,2023-08-18,17944969,0x32257d06a7e93ca0875eca1e339f6140a1e4d5b498aa...

In [7]:
print(len(export_df3))

1241995

In [8]:
export_df3.columns

Index(['Unnamed: 0', 'token_address', 'from_address', 'to_address', 'value',
       'transaction_hash', 'block_timestamp', 'block_number', 'block_hash'],
      dtype='object')

In [2]:
query4 = """ 
SELECT 
  address,
  is_erc20,
  is_erc721,
  DATE(block_timestamp) AS block_timestamp,
  block_number,

FROM
  bigquery-public-data.crypto_ethereum.contracts as contracts
WHERE
  address = '0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95'
  AND DATE(block_timestamp) >= '2017-08-18' AND DATE(block_timestamp) <= '2023-08-18'
  #block_timestamp > timestamp_sub(current_timestamp, INTERVAL 1 DAY)
ORDER BY block_timestamp
"""

In [3]:
df4 = pandas_gbq.read_gbq(
    query4, project_id=client.project, progress_bar_type='tqdm')

df4.head()

Downloading: |          |

Empty DataFrame
Columns: [address, is_erc20, is_erc721, block_timestamp, block_number]
Index: []